language: go

go: 
  - "1.13"

services:
  - docker

env:
  global:
    # docker credentials
    - secure: "MMDlT13nZPkJRlC6qXXYoxNJrwxoXFyzxJsipZhEE0YGza1kq/8spej9QroYlh5LgpJbcIOV0FtrKWF+5NYSY/dsNF/apKZkdgpemh7pDez8R6vaGCLoXvAnd5HAkyHv/uzrxUYAK9NuKBc4utZLMmsZxmY1HFd3M357WX6X6JpxxESPtMb7mdY5OZFmqnaNlde6p8zoo9oJmiG6Q0t52nhNaSY82Y2kf06e32IfgJiRwDzideLyVU1TH1YcSRXstT3m8/xPJQWDRKUNurbKeJnPJE/iga/fGNjvMaEtLcbSCE9g4AgyaJEfPgHGDFNCUQ3G7iovN6URNdk2Q8EJCaT6ZKDZAarWaF2SmUrnTWl1RjrjwnU7Yvvx4ls9b8iCEXAitXaSXqnz5M+yDKf33bO5mX1B4Skv7kPAdC4bHWtgndAOyfcLqUKbHntcYh2pGX61TBw7qD1mSVx3nItmIEvqKuP2dEmNc9nBO3lBD4CSRvNpKT1vT3S1wX25pblWvz1bV28LKuSPU5GzusaI/KJ2mv+YC2CTJ287tQd7xZSEFYaS2NT5irysT4awcJLvYXm6L1t2rC3XUAGGuBFMbTMJzRPCSyzuLStt66C0i83iLHmNIuCIsi0Yp02nvDuR+L1n5kl7NgSP7cc0bxSNQbzpv4ncruEHApLndK1N3Nw="
    - secure: "aFjBMVNpdvHKAMCrS0HUNLfytpIaq/QZfIO2zHctUKjRf5iw1ypmA7sqfKpsxuGJv0Z0jFUOOSH0qct9XtmESC0RRNeuSTaQoqKnxu6abAYm3DGf653C1/fAY4UN3yDxzjNzbVPickH2kTsgm/DDXvjwlsp6p70qnWQg4+ET2uqygT7jkoL+Hn51l+hOe5q/P/2gzd36PwVWXWsrCu9u9THVg44ghp3wB0lfkiaXcFq4bPjBJYWIGsTBUt+KQIxwhNPUiYgCH8Lv+A86U1SkROEAA+5kU3Wbr8Leq5XXzUbLAnqXPzYfvMAb6zdtkILwZv2yjzdUpyN5fXEoWrPkCMK6w2vPu1jIr0H4g8Dy6mTbj7ux4YWoLfbbhCU8r6/t0dpuzt+nRglgbIpKHnbGA3SVt1LBH4Cf6bGjO0jeyYi5V3m88jg8Ul+gmP6ZhkEs7YeRDjKpy6BGygoVYt9ZPvaw5nQI5j5mDH6ncdvZ/ZxNOlMUOVWPONoHGybXasW/lmdagXosO/mdwlFxhHhpts9WTxQV20p4Hc6QMK2xB31Pdg2KmwyTqRVe7d1T82PnWyozSKWSjJLZVGR2is1rnCrmRBV2UvOlePtsqoQT/IoWFQT/6yt8tLdcnj0l1c27nMcHQAZySw3c4MTqT8VKEKzosyLP7GE+kdktryuhvfk="

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin
  - golangci-lint --version

script:
  - make

before_deploy:
  - curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b $GOPATH/bin
  - seihon --version
  - |
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      docker login -u $DOCKER_USER -p $DOCKER_PASS
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: make publish-images
    on:
      tags: true
